### ISSUE TITLE
Bug问题及解决-ChatGPT 使用指南：相似匹配

### ISSUE THREAD

**Issue by leiya989** [datawhalechina/hugging-llm#19]
```
# 3.1 QA部分代码
try:
    info = index.info()
except:
    index.create_index(schema)

res = index.search(query, params_dict)
```
### **bug问题：**
您好，此处发现了一个小bug，即如果以这种形式创建索引，后面search的时候不会只在当前创建的索引里搜索，而是会在所有redis中存在的索引中搜索，原因在于create_index的时候需要指定将哪些前缀或者模式进行索引；
### **bug复现：**
可以再创建一个其他名称的index，写入相同内容，此时index.search会搜索出两个index中相同的内容
### **bug解决：**
在创建index时候指定之后要被索引的key，参考来源于 【https://redis.io/docs/clients/python/】

```
from redis.commands.search.indexDefinition import IndexDefinition
index.create_index(schema,
                       definition=IndexDefinition(
                           prefix=[INDEX_NAME+'-']
                       )
                       )
```

测试后发现问题修复

**Comment by hscspring** [comment]
非常感谢 @yanglei-github ，已修复。
