### ISSUE TITLE
第一章中的错别字问题：ChatGPT基础科普——知其一点所以然

### ISSUE THREAD

**Issue by kal1x** [datawhalechina/hugging-llm#22]
多看一步大不一样！看看概率最大的成谁了，久违了，再说一句「我喜欢你」。上面这种方法叫做Beam Search（中文叫集束搜索），简单来说就是一步多看几个词，看最终句子（比如生成到句号、感叹号或其他停止符号）的概率。刚刚我们的例子中，num_beams=2（只看了2个），看的越多，**约**不容易生成固定的文本。

- 看的越多，~~约~~**越**不容易生成固定的文本。

**Comment by hscspring** [comment]
已修改，谢谢~
