### ISSUE TITLE
chap2-相似匹配 部分代码有bug

### ISSUE THREAD

**Issue by kal1x** [datawhalechina/hugging-llm#25]
- 同一个 kernel 里面，用户的openai版本肯定是不变的，但是调用 completions 方法的时候，两个cell中的方法不一样
- openai.ChatCompletion.create 在超过1.0.0的版本中已经不支持了
  - [OpenAI API error: "You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0"](https://stackoverflow.com/questions/77505030/openai-api-error-you-tried-to-access-openai-chatcompletion-but-this-is-no-lon)](https://stackoverflow.com/questions/77505030/openai-api-error-you-tried-to-access-openai-chatcompletion-but-this-is-no-lon#/)
- <img width="1296" alt="image" src="https://github.com/datawhalechina/hugging-llm/assets/54575374/969f116f-8997-4f81-b069-cea770c9c49a">

**Comment by hscspring** [comment]
您好，感谢关注，我们已更新相关内容。
