### ISSUE TITLE
句词分类 3.1 文档问答中用到的 csv 无法从 wiki 获取

### ISSUE THREAD

**Issue by kriss-spy** [datawhalechina/hugging-llm#26]
我在学习hugging-llm 课程过程中，无法完整地从 wiki 爬取课程所需要的数据，学习受阻

学习章节为 hugging-llm 句词分类 3.1 文档问答，文字教程中使用的数据 olympics_sections.csv 来自 [openai-cookbook](https://github.com/openai/openai-cookbook/blob/1f6c2304b401e931928e74e978d9a0b8a40d1cf7/examples/fine-tuned_qa/olympics-1-collect-data.ipynb)

我注意到，"Extracting the data will take about half an hour, and processing will likely take about as much"
并且耐心等待出现报错

细节见：
[爬取wiki olympics数据的代码和报错信息.md](https://github.com/user-attachments/files/15800365/wiki.olympics.md)

经过一定的尝试，仍无法解决问题
希望能提供csv的直接下载渠道，或者指出我爬取过程的问题，十分感谢

**Comment by hscspring** [comment]
你好，同学，本项目用到的数据集都在项目里哦。
https://github.com/datawhalechina/hugging-llm/blob/main/content/chapter3/dataset/olympics_sections_text.csv

**Comment by kriss-spy** [comment]
感谢
不知道为什么，之在仓库里没找到

**Comment by hscspring** [comment]
> 感谢 不知道为什么，之在仓库里没找到

文档有content和docs两部分，前者是原稿，Notebook的，docs那个是书稿，Markdown的。
它们之间会有一些区别，但区别不大，不影响。
