### ISSUE TITLE
ChatGPT基础科普——知其一点所以然.md中缺少图1：如何预测下一个词

### ISSUE THREAD

**Issue by EdenLiu** [datawhalechina/hugging-llm#7]
请问：ChatGPT基础科普——知其一点所以然.md中是否缺少了图一

**Comment by Relph1119** [comment]
<img width="846" alt="微信截图_20230425085946" src="https://user-images.githubusercontent.com/15226799/234149194-87a87a2e-f4b7-45cd-9156-0877c9308cea.png">
图1的显示是正常的，可以把项目下载之后，单独打开该markdown文件进行学习
